name: safemind
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.9  # Add shared_preferences dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/back_spl.png
    - assets/images/search.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/static/Nunito-Regular.ttf
        - asset: assets/fonts/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Nunito-Italic.ttf
          style: italic
